// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPYLy7hz6P79Pc5Li5uuVFuveu5FS1Hk',
    appId: '1:333033764801:web:b152675c94ecec53516140',
    messagingSenderId: '333033764801',
    projectId: 'flutter2-ca2ea',
    authDomain: 'flutter2-ca2ea.firebaseapp.com',
    storageBucket: 'flutter2-ca2ea.firebasestorage.app',
    measurementId: 'G-4Q28RTQLNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xBUUQF8d0nM16sRvnEw0dO7oL2GF9y4',
    appId: '1:333033764801:android:bd0c32da721a3591516140',
    messagingSenderId: '333033764801',
    projectId: 'flutter2-ca2ea',
    storageBucket: 'flutter2-ca2ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhvnLKJ7T_TstdkP0gLmOBotUI9Y8AXl8',
    appId: '1:333033764801:ios:64cc339a09417d9c516140',
    messagingSenderId: '333033764801',
    projectId: 'flutter2-ca2ea',
    storageBucket: 'flutter2-ca2ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhvnLKJ7T_TstdkP0gLmOBotUI9Y8AXl8',
    appId: '1:333033764801:ios:64cc339a09417d9c516140',
    messagingSenderId: '333033764801',
    projectId: 'flutter2-ca2ea',
    storageBucket: 'flutter2-ca2ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIPYLy7hz6P79Pc5Li5uuVFuveu5FS1Hk',
    appId: '1:333033764801:web:51b57086e39f61ac516140',
    messagingSenderId: '333033764801',
    projectId: 'flutter2-ca2ea',
    authDomain: 'flutter2-ca2ea.firebaseapp.com',
    storageBucket: 'flutter2-ca2ea.firebasestorage.app',
    measurementId: 'G-PC39KPNTQ7',
  );
}
